<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Exceptions\ThrottleRequestsException;
use Illuminate\Validation\ValidationException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
        InternalException::class,
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {

        });
    }

    function render($request,  Throwable $e)
    {
        if ($e instanceof ValidationException) {
            return response()->json(['message' => current(current($e->errors()))])
                ->setStatusCode($e->status);
        }
        if ($e instanceof ThrottleRequestsException) {
            return response()->json(['message' => '操作频率过快，请一分钟后再试'])
                ->setStatusCode($e->getStatusCode());
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
